[package]
name = "fast-rich-python"
version = "0.3.2"
edition = "2021"

[lib]
name = "fast_rich"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py310"] }
fast-rich = { path = "../../", features = ["full"] }
